### ISSUE TITLE
ipgetter2 does not work on Python 3.5

### ISSUE THREAD

**Issue by Wicloz** [starofrainnight/ipgetter2#1]
* ipgetter2 version: 1.1.8
* Python version: 3.5.3
* Operating System: Debian 9.9

### Description

```
ip = IPGetter().get()
```

which leads to

```
Traceback (most recent call last):
  File "/etc/nginx/update-cloudflare-dns.py", line 10, in <module>
    ip = IPGetter().get()
  File "/usr/local/lib/python3.5/dist-packages/ipgetter2/ipgetter2.py", line 304, in get
    urls = random.choices(list(rest_urls), k=batch_size)
AttributeError: module 'random' has no attribute 'choices'
```

It would appear that `random.choices` is not present on Python 3.5.

**Comment by starofrainnight** [comment]
Thanks for your report! I will take a look later

**Comment by starofrainnight** [comment]
@Wicloz I released a new version 1.1.9 to pypi, could you give it a try?

**Comment by Wicloz** [comment]
This indeed works for me, thanks.
